import localFont from "next/font/local";
import "./styles.scss"
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import '@fortawesome/fontawesome-free/css/all.css';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Mallikarjun Appasha Katare",
  description: "Generated by Mallikarjun Appasha Katare. It is static webpage created in next js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
